### ISSUE TITLE
'RuntimeException' with message 'Function has already been defined'

### ISSUE THREAD

**Issue by marcaube** [padraic/humbug#131]
I have humbug installed as a global dependency on my computer using `composer global require humbug/humbug`. Now if I execute humbug in a repo where it was also installed as a dependency, I get a `RuntimeException` saying 'Function has already been defined'.

I can execute the local humbug just fine with `./vendor/bin/humbug`.

```txt
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Function has already been defined' in /home/foo/project/vendor/padraic/humbug_get_contents/src/function.php:35
```

**Comment by padraic** [comment]
@marcaube It's an issue with humbug_get_contents throwing an Exception because two files are clashing over the same function. Easy fix - I'll remove the exception ;).

**Comment by padraic** [comment]
A new 1.0.3 tag for that dependency is pushed - do a composer update and that should resolve the issue.

**Comment by marcaube** [comment]
The error is back since [this commit](https://github.com/padraic/phar-updater/commit/dfe1d25fcf1783d85f5e3998015a65851e52bc56) in `phar-updater` yesterday.

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Function has already been defined' in /home/foo/project/vendor/padraic/humbug_get_contents/src/function.php:25
```

**Comment by padraic** [comment]
Noted. I'm doing some work on phar-updater. Once that's done, the dependency will revert most likely to a new 1.0.4. I'll reopen here for tracking.

**Comment by padraic** [comment]
@marcaube This should now be fixed after a composer update ;)
