### ISSUE TITLE
Mutants marked as escaped when, not?

### ISSUE THREAD

**Issue by Anahkiasen** [padraic/humbug#23]
Maybe I'm not fully getting how to read the logs here so, might just be misunderstanding the docs.
Humbug ran and generated a log with 61 escaped mutants – in my mind those are the mutants that the tests did not catch (ie. all tests ran green when they shouldn't have).

However I tried to redo the changes of 3 or 4 of them and when running PHPUnit I do get failing tests.
Example diff:

```
-        return $this->usesStages && !empty($stages);
+        return $this->usesStages || !empty($stages);
```

Now if I redo that very change myself and run phpunit it seems to be caught as expected:

```
$ phpunit --stop-on-failure
PHPUnit 4.4.1 by Sebastian Bergmann.

There was 1 failure:

1) Rocketeer\Traits\BashModules\FlowTest::testCanCheckIfUsesStages
Failed asserting that true is false.
```

Am I just misunderstanding how to read the logs or is this a bug?

**Comment by padraic** [comment]
It's a bug. One of the upcoming changes is switching to processing TAP output - a defined format that I really should have used on Day 1. At present, there is a hack and slash processing of the actual text output as above. In this case, since we introduced --stop-on-failure, there is no guarantee of a progress line (i.e. a series of .EFSI characters).

**Comment by Anahkiasen** [comment]
Ok will wait a little bit before officially integrating Humbug to my test process and will watch on this issue. Amazing tool nonetheless, really eager to fully take advantage of it

**Comment by padraic** [comment]
I've implemented this (stupidly simple obvious should-have-been-done on Day 1) feature ;) https://github.com/padraic/humbug/commit/a7841e786c2feb4afcf36d0b67ba6f978d754ba1

Let me know how it goes - the TAP should always provide a "not ok" line on early interrupt.

**Comment by padraic** [comment]
@Anahkiasen We're slowly rounding out those rough edges ;).

**Comment by Anahkiasen** [comment]
Just tested with a7841e786c2feb4afcf36d0b67ba6f978d754ba1 and I'm still getting the error above in my escaped mutants – actually I'm still getting the same number of escaped mutants. Do I need to enable an option or pass a specific option? Could the way PHPunit is configured affect the results?

**Comment by Anahkiasen** [comment]
Could it be the test that makes it fail is not run for that particular mutation? How does Humbug decides which tests to run for a given mutation?

**Comment by Anahkiasen** [comment]
Actually no I don't think that's related. One of the mutations marked as escaped is this:

```
14) \Humbug\Mutator\Boolean\LogicalNot
Diff on ???::???() in /Users/anahkiasen/Sites/rocketeers/rocketeer/src/Rocketeer/RocketeerServiceProvider.php:
--- Original
+++ New
@@ @@
 // Define DS
-if (!defined('DS')) {
+if (defined('DS')) {
     define('DS', DIRECTORY_SEPARATOR);
 }
```

If I do that change, literally *all tests* fail, so shouldn't matter

**Comment by padraic** [comment]
Reopening to investigate

**Comment by padraic** [comment]
@Anahkiasen In terms of test decisions, we use code coverage data (PHP not HTML/XML) which lists the tests run per line of code, so we can cross reference to the mutated line and determine test classes to execute. You can usually find a copy in /tmp after humbug completes the initial test run prior to mutation testing - it tends to be a large file making up quite a chunk of humbug's memory usage.

**Comment by padraic** [comment]
@Anahkiasen Would you mind checking if still an issue? The current master has replaced a lot of the test selection code with a new package I've written for PHPUnit. I'm hoping it resolves all of these omitted test/incorrect escape issues.

**Comment by Anahkiasen** [comment]
Would but I can't, cause of #69 :p

**Comment by Anahkiasen** [comment]
But I think it's an issue on my end, will try to see what it is

**Comment by padraic** [comment]
@Anahkiasen I see what you did there ;).

**Comment by frickelbruder** [comment]
Same problem here. For example:
```
 \Humbug\Mutator\Arithmetic\Division
Diff on Pagination::calculateTotalPages() in /var/www/test/Pagination/Pagination.php:
--- Original
+++ New
@@ @@
     protected function calculateTotalPages($itemsPerPage, $totalItems) {
-        return ( int ) ceil( $totalItems / $itemsPerPage );
+        return ( int ) ceil( $totalItems * $itemsPerPage );
     }
```
Humbug tells me, that it was an escaped mutant. But if I change the code manually to "return ( int ) ceil( $totalItems * $itemsPerPage );" , phpunit throws multiple errors.

**Comment by frickelbruder** [comment]
My problem is equal to #94 
If I only run one suite, everything works as expected.
